### ISSUE TITLE
Get footy odds

### ISSUE THREAD

**Issue by jimmyday12** [jimmyday12/fitzRoy#10]

**Comment by jimmyday12** [comment]
@anoafl To chat to Betfair and Points bet about including the data

**Comment by Jack-FG** [comment]
How far did you get with this @jimmyday12 & @anoafl

**Comment by cfranklin11** [comment]
This issue is a little old, but if you're still looking to add betting odds, I've been scraping them from [Footywire](https://www.footywire.com/afl/footy/afl_betting). It's a bit messy, but my scraping code is here: https://github.com/tipresias/bird-signs/blob/master/afl_data/R/betting-odds.R.

I'd be happy to clean it up and open a PR if you're interested.

**Comment by anoafl** [comment]
Hi Craig, 

I think this would be a cool pull request. 

Apologies for late response.

**Comment by cfranklin11** [comment]
No worries. I'll get started on it and open a PR when it's ready.

**Comment by jimmyday12** [comment]
Hi @cfranklin11 - thanks for this, I've been away the last month so just catching up on all of the comments/pr's etc over the next few days
