### ISSUE TITLE
Home and Away Status for Finals

### ISSUE THREAD

**Issue by Jack-FG** [jimmyday12/fitzRoy#25]
Lads,

Just checking if there is an easy way to correct the home and away status of a team in finals. For example in the 2017 EF WCE vs Port. The game was played at Adelaide Oval but comes through as a WCE home game (when should be Port).

I think this is just a feature of scraping game results from AFL Tables who have the same issue. Thoughts on how to correct without manually doing?

**Comment by jimmyday12** [comment]
Interesting - thanks for pointing out! I found something kind of similar recently (was to do with extra time in a final that caused a funky table). I'm actually becoming more convinced that `fitzRoy` should be less opinionated about data errors in afltables like this. Partially because I don't want to code something to fix all of the different niche errors which may be fixed by afltables later on and then break the code. Also in case other people have fixed them manually knowing that afltables was wrong. 

I know that Paul from afltables is willing to receive emails about errors so I might hit him up about this one and maybe even keep a list on here of ones that other people find to keep sending him! I've create a new label for now and will keep you posted on what Paul says.

**Comment by jimmyday12** [comment]
This should be fixed by the latest commit https://github.com/jimmyday12/fitzRoy/commit/c160cc577e1b52d8548cdabdb2de77d243a7eac4

**Comment by ergasia2000** [comment]
@jimmyday12 still seems to be an issue for me on `0.3.2` - see attached.

![fitzroy](https://user-images.githubusercontent.com/68768661/88450858-cc7d7380-ce84-11ea-9125-2251d099e720.png)

Either way thanks for the great project.
