### ISSUE TITLE
Error message with get_afltables_stats

### ISSUE THREAD

**Issue by gswebstr** [jimmyday12/fitzRoy#32]
Tried to use the new get_afltables_stats function, and get an error as per below. Can you give any advice on why the error is occuring? Thanks

![snip_fitzroy_get_afltables_stats](https://user-images.githubusercontent.com/3703864/44262425-603c7300-a25e-11e8-828d-394a7bd6dfb1.JPG)

**Comment by jimmyday12** [comment]
Hi @gswebstr - I can't seem to replicate this issue but it seems like the installation of the package is corrupted. My best guess is to maybe remove the package and then try and reinstall. Are you able to restart your R session and then try the following?

`remove.packages("fitzRoy")`
`devtools::install_github("jimmyday12/fitzRoy")`

**Comment by gswebstr** [comment]
Thanks, that seems to work.

After reinstalling the package, there is a warning message

"Unknown Columns : Subsititute"

From a quick look at the file, it appears that column subsititute has NA
for 2017 and 2018.

Not an issue as not a variable I use.

Thanks for your assistance and great package.

**Comment by jimmyday12** [comment]
Ah yes - that's a small bug that I should fix (just quieten the message). Relates to the few years where we had the 'substitute'. That column exists for those years but then when I bind the new data onto that old data frame it throws an error because it can't find that column in recent years. Just needs a line of code to quieten the message. I'll start another issue for that and try fix it for a future version. 

Glad the reinstall helped!
