### ISSUE TITLE
Round 5 Melbourne and Richmond Wrong Round

### ISSUE THREAD

**Issue by Jack-FG** [jimmyday12/fitzRoy#54]
24/04/2019 Date of game is allocated to round 5. Hence there are 2 round 5 entries for 2019 for Melbourne & RFC. Needs to be allocated to round 6.

**Comment by jimmyday12** [comment]
Ah I thought this might catch me out. Thanks for picking up.

There isn't actually any way on the page I'm using to scrape the fixture (https://www.footywire.com/afl/footy/ft_match_list) to programatically know which round each upcoming match is in. 

As such, I've been using a heuristic to hack it. The heuristic is basically that all games between Thursday and Wednesday, inclusive, belong in the same round. This means that a game on a Wednesday will be counted as the last game of the round rather than the first game of the next round. This worked in 2018, where the only Wednesday game (ANZAC Day), was the last game of round 5. Given how rare they were, I figured it was how they always did it.

Looking back a bit though, the last Wednesday game before last year was also ANZAC day in 2012 and it was the first game of the round. In fact, looking through all history, all Wednesday games are the first one of the round (and sometimes there are multiple, like 1990 ANZAC day). 

Given that, I'll update the code to reflect that Wednesday games are always the first rather than the last round of the game, and put an exception for 2018.

Thanks @Jack-AFL

**Comment by Jack-FG** [comment]
@jimmyday12 Sounds good mate. There are always exceptions to the rule unfortunatley!

**Comment by cfranklin11** [comment]
I found a related problem with fixture data for 2012. The first match of the season is on Sat. 24 March, and the second is on Thur. 29 March, so the heuristic puts them in separate rounds even though they're both part of the first round, which shifts all later rounds by one (e.g. round 3 is labelled round 4).

Could you could include an exception for that year as well? Thanks!

Update: I've since found the same problem in seasons 2013 and 2014. Apparently the AFL was really into stretching out round 1 for a few years. All seasons after 2014 follow the Thur-to-Wed rule, however.
